name: Docker Image CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        # env:
        #  DOCKER_USER: shyamayadav154
        #  DOCKER_PASS: Shyam@154
        run: |
         docker login -u shyamayadav154 -p Shyam@154
         
      - name: docker build
        run : docker build . --file Dockerfile --tag test
        
      - name: docker push  
        run: |
         docker push test
        