name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker

        uses: docker/login-action@v2
        with:
          username: shyamayadav154
          password: Shyam@154

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shyamayadav154/create-and-test
          cache-from: type=registry,ref=shyamayadav154/create-and-test
          cache-to: type=registry,ref=shyamayadav154/create-and-test,mode=max

      

#
# test
#
