name: build and push image to docker hub

on: [push]

jobs:
  build-dh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: shyamayadav154
          password: Shyam@154
          image_name: hello-world
          push_git_tag: true
      
