name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        # env:
        #   DOCKER_USERNAME: shyamayadav154
        #   DOCKER_PASSWORD: Shyam@154
        with:
          username: shyamayadav154
          password: Shyam@154
      - name: Build the Docker image
        run: docker build -t shyamayadav154/myimage:latest .
      - name: Push the Docker image
        run: docker push shyamayadav154/myimage:latest
# After adding secrets in github repo,
# comment out env, and replace $DOCKER_USERNAME with ${{ secrets.DOCKER_USERNAME }} and $DOCKER_PASSWORD with ${{ secrets.DOCKER_PASSWORD }}
#
#  with:
#   username: ${{ secrets.DOCKER_USERNAME }}
#   password: ${{ secrets.DOCKER_PASSWORD }}
